name: ci hugo
on:
  push:
    branches: main

jobs:
  terraform:
    name: Run terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      ARM_CLIENT_ID: ${{secrets.TF_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_TENANT_ID}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -var resourcegroup=${{secrets.RESOURCEGROUP}} -var storageaccountname=${{secrets.STORAGEACCOUNTNAME}} -var proxyname=${{secrets.PROXYNAME}}
      - name: Terraform apply
        run: terraform apply -auto-approve -var resourcegroup=${{secrets.RESOURCEGROUP}} -var storageaccountname=${{secrets.STORAGEACCOUNTNAME}} -var proxyname=${{secrets.PROXYNAME}}
  function:
    name: Publish function
    runs-on: ubuntu-latest
    needs: terraform
    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: ./function/AuthProxy
      AZURE_FUNCTIONAPP_NAME: ${{secrets.PROXYNAME}}
      DOTNET_VERSION: 3.1.x
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Run dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
  hugo:
    name: Publish hugosite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hugo/quickstart
    steps:
      - uses: actions/checkout@v2
      - uses: chabad360/hugo-actions@master
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: 'public'
          container_name: 'content'
          connection_string: ${{ secrets.STORAGE_CREDENTIALS }}
          sync: true
