name: ci hugo
on:
  push:
    branches: main

jobs:
  terraform:
    name: Run terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      ARM_CLIENT_ID: ${{secrets.TF_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_TENANT_ID}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve -var resourcegroup=${{secrets.RESOURCEGROUP}} -var storageaccountname=${{secrets.STORAGEACCOUNTNAME}} -var proxyname=${{secrets.PROXYNAME}}